### ISSUE TITLE
Configuration for persistent data of mysql

### ISSUE THREAD

**Issue by kopax** [cema-sp/iredmail-docker#7]
_conf :_
**Docker version 1.8.2, build 0a8c2e3**
**Linux prod-01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux**

I am trying to install `cema-sp/iredmail-docker with this docker-compose.yml file :

```
iredmail:
  image: cema/iredmail:example
  hostname: mail
  domainname: ilovesports.com
  privileged: true
  volumes:
    - /srv/docker/iredmail/backups:/backups:rw
    - /srv/docker/iredmail/mysql:/var/lib/mysql:rw
  ports: 
    - "25:25"
    - "80:80" 
    - "587:587"
    - "110:110"
    - "143:143"
    - "389:389"
    - "443:443"
    - "995:995"
    - "993:993"
    - "636:636"
```

When running the container got stuck on :

```
[~/iredmail]: docker-compose stop && docker-compose up
Stopping iredmail_iredmail_1... done
Starting iredmail_iredmail_1...
Attaching to iredmail_iredmail_1
```

Container start but mysql service is stopped, test from inside the container : 

```
root@mail:/var/lib# service mysql status
MySQL is stopped..
root@mail:/var/lib# service mysql start
Starting MySQL database server: mysqld . . . . . . . . . . . . . . failed!
```

Container logs only has  `Attaching to iredmail_iredmail_1`

Content of folder `/srv/docker` on host is owned by `root:docker`

Content of folder `/srv/docker/iredmail/mysql` is empty

I have tried without mounting `/var/lib/mysql` and it worked, do you guy have the same issue ?

Last question, do I have any other volumes to mount so it won't lose any data on restart ?
